config/routes.rb
Rails.application.routes.draw do
  resources :campaigns, only: [:new, :create, :show, :edit, :destroy] do
    resources :publishings, only: :create
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    can :manage, Campaign do |camp|
      camp.user == user
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :rewards, dependent: :destroy

  # reject_if: :all_blank will ignore any associated rewards attributes if they
  #            are all blank (meaning user didn't enter anything in the fields)
  accepts_nested_attributes_for :rewards, reject_if: :all_blank,
                                          allow_destroy: true

  validates :rewards, length: {
                                  minimum: 2,
                                  maximum: 10,
                                  message: 'Please supply 2 to 10 rewards'
                                 }

  belongs_to :user, optional: true
  validates :title, presence: true, uniqueness: true

  geocoded_by :address
  after_validation :geocode # this will make an HTTP request to Google to get
                            # the coordinates for the addrses

  def has_map?
    longitude.present? && latitude.present?
  end

  include AASM

  aasm whiny_transitions: false do
       state :draft, initial: true
       state :published
       state :cancelled
       state :funded
       state :unfunded

       event :publish do
         transitions from: :draft, to: :published
       end

       event :fund do
         transitions from: :published, to: :funded
       end

       event :unfunded do
         transitions from: :published, to: :unfunded
       end

       event :cancel do
         transitions from: [:published, :funded], to: :cancelled
       end

       event :relaunch do
         transitions from: :cancelled, to: :draft
       end

     end

    end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :campaign, optional: true
  validates :title, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :campaigns, dependent: :nullify

  validates :email, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def authenticate_user!
    redirect_to root_path unless user_signed_in?
  end

  def current_user
    @current_user ||= User.find session[:user_id] if user_signed_in?
  end
  helper_method :current_user
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!

  def new
    @campaign = Campaign.new
    3.times { @campaign.rewards.build }
  end

  def create
    @campaign = Campaign.new campaign_params
    @campaign.user = current_user
    if @campaign.save
      redirect_to campaign_path(@campaign), notice: 'Campaign created!'
    else
      render :new
    end
  end

  def show
    @campaign = Campaign.find params[:id]
  end

  def edit
    @campaign = Campaign.find params[:id]
    redirect_to root_path unless can? :edit, @campaign
  end

  def destroy
    campaign = Campaign.find params[:id]
    campaign.destroy
  end

  private

  def campaign_params
    params.require(:campaign).permit(:title,
                                     :body,
                                     :goal,
                                     :end_date,
                                     { rewards_attributes: [ :title,
                                                             :body,
                                                             :amount,
                                                             
                                                             ]
                                     })
  end
end

app/controllers/publishings_controller.rb
class PublishingsController < ApplicationController
  before_action :authenticate_user!

  def create
    campaign = Campaign.find params[:campaign_id]
    if campaign.publish!
      redirect_to campaign, notice: 'Campaign is published!'
    else
      redirect_to campaign, notice: 'Can\'t publish campaign, already published?'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Thank you for signing in'
    else
      flash.now[:alert] = 'Wrong credentials!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Signed Out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Thank you for signing up'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit([:first_name,
                                  :last_name,
                                  :email,
                                  :password,
                                  :password_confirmation])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/publishings_helper.rb
module PublishingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/campaigns/_reward_fields.html.erb
<div class="nested-fields">
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.input :amount%>
  <%= link_to_remove_association 'Remove Reward', f %>
  <hr>
</div>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= simple_form_for @campaign do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.input :goal %>
  <%= f.input :end_date %>

  <%# this create fields that help us create the nested records
      which are rewards it will use the proper naming convention
      for them so they work properly with Rails controller %>
<%= f.error :rewards %>
<div class='rewards'>
  <%= f.simple_fields_for :rewards do |r| %>
    <%= render 'reward_fields', f: r  %>
  <% end %>
  <div class="links">
    <%= link_to_add_association 'Add Reward', f, :rewards %>
  </div>
</div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/campaigns/show.html.erb
<h1><%= @campaign.title %></h1>
<p><%= @campaign.body %></p>
<p>Goal: <%= number_to_currency @campaign.goal %></p>
<p>End Date: <%= @campaign.end_date %></p>

<% if @campaign.may_publish? %>
  <%= link_to 'Publish', campaign_publishings_path(@campaign), method: :post %>
<% end %>

<% if @campaign.has_map? %>
  <div style='width: 800px;'>
    <div id="map" style='width: 800px; height: 400px;'></div>
  </div>
<% end %>

<% @campaign.rewards.each do |reward| %>
  <div class="well col-md-4">
    <h3><%= reward.title %></h3>
    <p><%= reward.body %></p>
    <p><%= number_to_currency reward.amount %></p>
  </div>
<% end %>


<% if @campaign.has_map? %>
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": <%= @campaign.latitude %>,
      "lng": <%= @campaign.longitude %>,
      // "picture": {
      //   "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
      //   "width":  32,
      //   "height": 32
      // },
      "infowindow": '<%= @campaign.title %>'
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(17);
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fundsy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <script src="//maps.google.com/maps/api/js?key=AIzaSyCAS6cmwR-3cE7E5spvo3Ue7jGh19TcPHI"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


  </head>

  <body>

    <% if user_signed_in? %>
      Hello <%= current_user.first_name %>,
      <%= link_to 'Sign Out', sessions_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign Up', new_user_path %>
      |
      <%= link_to 'Sign In', new_session_path %>
    <% end %>
    <hr>
    <% if flash[:notice] %>
      <div class="flash-notice"><%= flash[:notice] %></div>
    <% elsif flash[:alert] %>
      <div class="flash-alert"><%= flash[:alert] %></div>
    <% end %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :password, required: true %>
  <%= f.input :password_confirmation, required: true %>
  <%= f.submit 'Sign Up', class: 'btn btn-primary' %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Fund.sy</h1>

<%= link_to 'New Campaign', new_campaign_path %>